// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetencionesRG830.Infrastructure.Persistencia;

#nullable disable

namespace RetencionesRG830.Infrastructure.Migrations
{
    [DbContext(typeof(RetencionesRG830DbContext))]
    [Migration("20260828012125_AgregarBaseCalculoAcumulada")]
    partial class AgregarBaseCalculoAcumulada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CargoFirmante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreFirmante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cuit")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.Operacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseCalculoAcumulada")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaComprobante")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaRetencion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteComprobante")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteGravado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoRetenido")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroCertificado")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NumeroComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntoVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegimenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoComprobante")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("RegimenId");

                    b.HasIndex("ClienteId", "NumeroCertificado")
                        .IsUnique();

                    b.ToTable("Operaciones");
                });

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("InscriptoEnGanancias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Cuit")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.Regimen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimoRetencion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimoRetencionNoInscripto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(240m);

                    b.Property<decimal>("MontoNoSujetoARetencion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TasaInscripto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TasaNoInscriptoHumana")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TasaNoInscriptoResto")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoCalculo")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("VigenciaHasta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "VigenciaDesde")
                        .IsUnique();

                    b.ToTable("Regimenes");
                });

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.TramoEscala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Desde")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Hasta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoFijo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegimenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegimenId");

                    b.ToTable("TramosEscala");
                });

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.Operacion", b =>
                {
                    b.HasOne("RetencionesRG830.Domain.Entidades.Cliente", "Cliente")
                        .WithMany("Operaciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RetencionesRG830.Domain.Entidades.Proveedor", "Proveedor")
                        .WithMany("Operaciones")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RetencionesRG830.Domain.Entidades.Regimen", "Regimen")
                        .WithMany("Operaciones")
                        .HasForeignKey("RegimenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Proveedor");

                    b.Navigation("Regimen");
                });

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.Proveedor", b =>
                {
                    b.HasOne("RetencionesRG830.Domain.Entidades.Cliente", "Cliente")
                        .WithMany("Proveedores")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.TramoEscala", b =>
                {
                    b.HasOne("RetencionesRG830.Domain.Entidades.Regimen", "Regimen")
                        .WithMany("Tramos")
                        .HasForeignKey("RegimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regimen");
                });

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.Usuario", b =>
                {
                    b.HasOne("RetencionesRG830.Domain.Entidades.Cliente", "Cliente")
                        .WithMany("Usuarios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.Cliente", b =>
                {
                    b.Navigation("Operaciones");

                    b.Navigation("Proveedores");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.Proveedor", b =>
                {
                    b.Navigation("Operaciones");
                });

            modelBuilder.Entity("RetencionesRG830.Domain.Entidades.Regimen", b =>
                {
                    b.Navigation("Operaciones");

                    b.Navigation("Tramos");
                });
#pragma warning restore 612, 618
        }
    }
}
